server:
  port: 9090
spring:
  web:
    resources:
      static-locations:
        - classpath:/ui
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
